### ISSUE TITLE
conda forge

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#69]
We should get discretize up on conda-forge (https://conda-forge.org/docs/recipe.html). This will help overcome many of the installation issues we keep encountering with windows machines, as described in #32 (cc @sdevriese, @yangdikun). 

@leouieda has experience submitting recipes and can hopefully help :)

**Comment by leouieda** [comment]
This simple changed completely stopped all emails about Windows install errors. It's very healthy for a persons inbox.

**Comment by leouieda** [comment]
Hey, I was taking a look at the setup.py and requirements files. We'll need packages for `properties` and `pymatsolver` first in order to get discretize. I don't think you can have non-conda pkg dependencies specified. 

`properties` seems to be pure Python so that would not be a problem. We can probably start there.

@rowanc1 `pymatsolver` requires MUMPS right? There is a [conda-forge feedstock for mumps](https://github.com/conda-forge/mumps-feedstock) but it  has no  package for Windows yet. So if this is a required dependency we need to get MUMPS on Windows before anything else can happen on `discretize`.

**Comment by rowanc1** [comment]
`pymatsolver` works without mumps as well, just can also add that solver if it is available.

**Comment by rowanc1** [comment]
Check out aranzgeo/properties#179 which helps with this issue! Thanks @fwkoch!!

**Comment by lheagy** [comment]
@sgkang, how are things going here? Do you have some ideas on how we might get started with this?

**Comment by sgkang** [comment]
I am about to start handling this issue. 
It seems like a generic problem with windows machine + python3. 
I just got a new windows machine, and having same problem.

**Comment by Kapondo** [comment]
Has anyone successfully managed to install simpeg on Windows 7 64bit + Python 3.6? I am battling. I have Visual Studio Community 2017, but my Python was installed using Anaconda.
I am having the below error message:

Compiling C:\Users\kapondot\AppData\Local\Temp\easy_install-ny76pgjg\discretize-0.1.11\discretize\utils\interputils_cython.pyx because it depends on C:\Users\kapondot\Anaconda3\lib\site-packages\Cython\Includes\numpy\__init__.pxd.
[1/1] Cythonizing C:\Users\kapondot\AppData\Local\Temp\easy_install-ny76pgjg\discretize-0.1.11\discretize\utils\interputils_cython.pyx
TreeUtils.c
c:\users\kapondot\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
error: Setup script exited with error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\
Users\kapondot\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\kapondot\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\kapondot\Anaconda3\include -IC:\Users\kapondot\Anaconda3\inc
lude -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.258
27\include" /Tcdiscretize\TreeUtils.c /Fobuild\temp.win-amd64-3.6\Release\discretize\TreeUtils.obj" failed with exit status 2

**Comment by thast** [comment]
Hi @Kapondo,
How do you try to install discretize, With pip or with a clone of the repository?
Thanks

**Comment by thast** [comment]
@dccowan : you work on Windows 7 right?

**Comment by Kapondo** [comment]
I have been trying to do it with the clone of the repository.
Yes I am using Windows 7, 64 bit

**Comment by Kapondo** [comment]
@dccowan,

Thank you very much for a quick response. I have been trying to install
discretize with a clone of the repository.

Regards


Best Regards
--------------------------------------------------------------------------------------------------------------------------------------

*Tongesai Kapondo*

20 Camelot
176 Helen Road
Strathavon
Sandton
2196 Johannesburg

C +27 79 508 8233
T +27 11 783 0163

E t.kapondo@gmail.com
Skype: kapondot
LinkedIn: https://za.linkedin.com/in/t-kapondo-86360b55

--------------------------------------------------------------------------------------------------------------------------------------
*"A computer program is said to learn from experience E with respect to
some task T and some performance P, if its performance P on task T, as
measured by P, improves with experience E"*

Tom Mitchell, 1997

**Comment by lheagy** [comment]
@sgkang: I know you started looking into getting it up on conda forge - have you had any luck with that?

**Comment by thast** [comment]
@Kapondo:
What will be your use of discretize?

If you think of mostly using it at first, try `pip install discretize` and let us know if it works for you. If not, I will ask @dccowan to build a wheel file for you (and then you can do `pip isntall *.whl`)

If you think of contributing (Awesome! :D ), we can try diving more on the visual studio issue. I know that in some cases, the MinGW compiler has worked beautifully where VS failed.

**Comment by Kapondo** [comment]
I am trying to install simpeg and I believe it requires discretize on installation. I could not find the correct `*.whl` for Win64, Python 3.6.
I am still battling with no success!

**Comment by Kapondo** [comment]
I am using Windows 7 64bit

**Comment by Kapondo** [comment]
I have tried `pip install discretize`, but unfortunately, it doesn't work.

**Comment by Kapondo** [comment]
Trying `pip install discretize` , I get the following error message:
(C:\Users\kapondot\Anaconda3) C:\Users\kapondot>pip install discretize
Collecting discretize
Exception:
Traceback (most recent call last):
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

**Comment by thast** [comment]
@Kapondo:
Download the wheel file I built for discretize: https://github.com/thast/Benchmarks_files/raw/master/dist/discretize-0.1.11-cp36-cp36m-win_amd64.whl

Then run `pip install discretize-0.1.11-cp36-cp36m-win_amd64.whl` (inside the folder with the file or with the correct path to it)

It was done with a Windows 10 machine but should work for Windows 7 as well.

**Comment by thast** [comment]
Update: the *.whl has been uploaded on PyPi, so even a `pip install discretize` should be working now.

**Comment by Kapondo** [comment]
Thank you @thast for the correct `*.whl`. It seems I can see it now and progressed to another level in installing simpeg. However, I still have a problem with installing simpeg as shown below:

Installed c:\users\kapondot\anaconda3\lib\site-packages\simpeg-0.6.5-py3.6.egg
Processing dependencies for SimPEG==0.6.5
**Searching for discretize**
Reading https://pypi.python.org/simple/discretize/
**Downloading** https://pypi.python.org/packages/34/65/5914caaf1b8523431306b5d4eeb78715eaf213d5418b5d4a47308d3f891e/discretize-0.1.11.tar.gz#md5=bbd76bffff3e525a9c4db8a37ffcff94
Best match: `discretize 0.1.11`
**Processing discretize-0.1.11.tar.gz**
Writing C:\Users\kapondot\AppData\Local\Temp\easy_install-8ovfku13\discretize-0.1.11\setup.cfg
Running discretize-0.1.11\setup.py -q bdist_egg --dist-dir C:\Users\kapondot\AppData\Local\Temp\easy_install-8ovfku13\discretize-0.1.11\egg-dist-tmp-hvabxsug
Compiling C:\Users\kapondot\AppData\Local\Temp\easy_install-8ovfku13\discretize-0.1.11\discretize\utils\interputils_cython.pyx because it depends on C:\Users\kapondot\Anaconda3\lib\site-packages\Cython\Includes\numpy\__init__.pxd.
[1/1] Cythonizing C:\Users\kapondot\AppData\Local\Temp\easy_install-8ovfku13\discretize-0.1.11\discretize\utils\interputils_cython.pyx
**TreeUtils.c**
c:\users\kapondot\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
error: Setup script exited with error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\
Users\kapondot\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\kapondot\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\kapondot\Anaconda3\include -IC:\Users\kapondot\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.258
27\include" /Tcdiscretize\TreeUtils.c /Fobuild\temp.win-amd64-3.6\Release\discretize\TreeUtils.obj" failed with exit status 2

I am using: 

- Windows 7 64bit 
- Python 3.6.3 
- Microsoft Visual Studio Community 2017

Your help most appreciated!

**Comment by thast** [comment]
@Kapondo : Nice, getting closer! :) 
Sorry for asking again, is this what you get when doing `pip install simpeg`? If not, can you try it?

For testing, I created a brand new environment in Conda on my windows 10 machine, so clean of discretize and simpeg. `pip install simpeg` worked nicely, and `pip `was smart enough to grab the correct .whl from PyPi for `discretize` (now that is been uploaded).

In your case, I am not an expert in `pip` but I see 2 things:
- simpeg is loaded from an .egg file on your machine, probably from a previous attempt
- then it still tries to load the .tar.gz file for `discretize` that we had trouble with previously.
So my best guess is that this .egg file forces you to load the .tar.gz. 

If you were already using `pip` for `simpeg` and got this error, I would try to do `pip uninstall simpeg` (might error saying `simpeg not installed`) first or get rid of the egg file to start fresh, and then try again to run `pip install simpeg`

@lheagy, @rowanc1  : Any other thought about it?

**Comment by Kapondo** [comment]
@thast I am sorry for the tardy response as I have been traveling. Thank you very much for all your suggestions above. I have tried all the above but with no success. I deleted the whole simpeg folder package which was installed from the source. 
When I tried to install using `pip install simpeg` I got the below error message, that is why I went the route of installing from the source.

(C:\Users\kapondot\Anaconda3) C:\>pip install SimPEG
**Collecting SimPEG**
Exception:
Traceback (most recent call last):
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\kapondot\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

Again I do have to mention that I am using the below:

* Windows 7 64bit
* Python 3.6.3 installed using Anaconda
* Microsoft Visual Studio Community 2017


Your help and suggestions are much appreciated!

**Comment by thast** [comment]
Hi @Kapondo, 
This does not look like a problem related to `SimPEG` or `discretize` anymore (never show up in the error log) but directly with `pip`.
Googling it, I found this stackoverflow question with what seem exactly the same error message as you. See the link: http://goo.gl/SqsTq1
The most popular solution is to update pip with conda: `conda install pip`

Hope this helps.

**Comment by lheagy** [comment]
Hi @Kapondo, I am sorry this is still a cumbersome process! 

I agree with @thast's comment above, it doesn't look like this issue is specific to `discretize` or `SimPEG`. If the above suggestions don't work, you might try
```
pip install --upgrade pip
```

**Comment by Kapondo** [comment]
@lheagy & @thast. Thank you so very much. I have successfully managed to` pip install simpeg` now. I will be testing the package next time. I really appreciate all your help.

**Comment by Kapondo** [comment]
My problem was to do with `pip`. After following @thast 's suggestion, my problem was solved. Thanks a million!

**Comment by lheagy** [comment]
I have a first pass of the conda-forge recipe started at conda-forge/staged-recipes#6891. @leouieda or @fwkoch: if you have any input on that pr, your advice would be much appreciated 😄

**Comment by lheagy** [comment]
closed with the help of @ocefpaf in conda-forge/staged-recipes#9236 🎉
